costmap_filter_preferred_lanes:
  ros__parameters:
    use_sim_time: true
    type: 0
    filter_info_topic: "/costmap_filter_info_preferred"
    mask_topic: "/preferred_filter_mask"
    base: 0.0
    multiplier: 1.0
preferred_lanes_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/preferred_filter_mask"
    yaml_filename: "preferred_lanes_mask.yaml"
