costmap_filter_speed:
  ros__parameters:
    use_sim_time: true
    type: 1
    filter_info_topic: "/costmap_filter_info_speed"
    mask_topic: "/filter_mask"
    base: 100.0
    multiplier: -1.0
speed_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/filter_mask"
    yaml_filename: "speedlimit_mask.yaml"  
    # istenilen hız yüzdeliği * 2.56 = Renk