controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: True

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    publish_frequency: 30

    base_frame_id: base_footprint
    odom_frame_id: odom

    enable_odom_tf: false

    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    wheel_seperation: 0.16
    wheel_radius: 0.033

    use_stamped_vel: false

    cmd_vel_timeout: 0.5

    linear:
      x:
        has_velocity_limits: True
        max_velocity: 10.0
        min_velocity: -10.0

        has_acceleration_limits: True
        max_acceleration: 1.0
        min_acceleration: -10.

    angular:
      z:
        has_velocity_limits: True
        max_velocity: 10.0
        min_velocity: -10.0

        has_acceleration_limits: True
        max_acceleration: 1.0
        min_acceleration: -1.0
